export const homePageData = [
  {
    id: 1,
    title: "Quick Chat",
    description: "Start a new conversation instantly",
    icon: "💬",
    link: "/chat/new",
    bgColor: "bg-white",
    hoverColor: "hover:bg-slate-50",
    borderColor: "border border-slate-200",
    buttonVariant: "default",
    buttonText: "Start Chat",
  },
  {
    id: 2,
    title: "Group Chat",
    description: "Create or join group conversations",
    icon: "👥",
    link: "/groups",
    bgColor: "bg-white",
    hoverColor: "hover:bg-slate-50",
    borderColor: "border border-slate-200",
    buttonVariant: "default",
    buttonText: "Explore Groups",
  },
  {
    id: 4,
    title: "Voice Chat",
    description: "Audio-only conversations",
    icon: "🎤",
    link: "/voice-chat",
    bgColor: "bg-white",
    hoverColor: "hover:bg-slate-50",
    borderColor: "border border-slate-200",
    buttonVariant: "default",
    buttonText: "Start Voice",
  },
  {
    id: 5,
    title: "Saved Messages",
    description: "Access your bookmarked chats",
    icon: "📌",
    link: "/saved",
    bgColor: "bg-white",
    hoverColor: "hover:bg-slate-50",
    borderColor: "border border-slate-200",
    buttonVariant: "default",
    buttonText: "View Saved",
  },
  {
    id: 6,
    title: "Settings",
    description: "Customize your chat experience",
    icon: "⚙️",
    link: "/settings",
    bgColor: "bg-white",
    hoverColor: "hover:bg-slate-50",
    borderColor: "border border-slate-200",
    buttonVariant: "default",
    buttonText: "Configure",
  },
];

export const features = [
  {
    id: 1,
    icon: "🔒",
    title: "Secure Messaging",
    description: "End-to-end encryption for your privacy",
  },
  {
    id: 2,
    icon: "⚡",
    title: "Real-time Chat",
    description: "Instant message delivery",
  },
  {
    id: 3,
    icon: "🌐",
    title: "Cross-platform",
    description: "Chat from any device, anywhere",
  },
];

export const statistics = [
  {
    id: 1,
    value: "2k+",
    label: "Active Users",
  },
  {
    id: 2,
    value: "100k+",
    label: "Messages Sent",
  },
  {
    id: 3,
    value: "5+",
    label: "Countries",
  },
];
